import { ScrollView, Text, View, TouchableOpacity, ActivityIndicator } from "react-native";
import { router } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { LoadingScreen } from "@/components/loading-screen";
import { useAuth } from "@/hooks/use-auth";
import { useColors } from "@/hooks/use-colors";
import { useEffect } from "react";

export default function HomeScreen() {
  const { user, loading } = useAuth();
  const colors = useColors();

  useEffect(() => {
    if (!loading && !user) {
      router.replace("/welcome");
    }
  }, [user, loading]);

  if (loading) {
    return <LoadingScreen message="Loading your dashboard..." />;
  }

  if (!user) {
    return null; // Will redirect in useEffect
  }

  const features = [
    {
      icon: "🤖",
      title: "AI Meal Planning",
      description: "Get personalized meal plans generated by AI based on your family's preferences and dietary restrictions.",
      available: true,
      action: () => router.push("/generate-plan"),
    },
    {
      icon: "👨‍👩‍👧‍👦",
      title: "Family Voting",
      description: "Let everyone in the family vote on meal options. Democracy at the dinner table!",
      available: true,
      action: () => router.push("/dashboard"),
    },
    {
      icon: "🥗",
      title: "Dietary Preferences",
      description: "Set dietary restrictions, allergies, and preferences for each family member.",
      available: true,
      action: () => router.push("/onboarding"),
    },
    {
      icon: "📋",
      title: "Shopping Lists",
      description: "Automatically generate shopping lists based on your weekly meal plan.",
      available: true,
      action: () => router.push("/dashboard"),
    },
    {
      icon: "📊",
      title: "Nutrition Tracking",
      description: "Track nutritional information and ensure balanced meals for your family.",
      available: false,
    },
    {
      icon: "🌍",
      title: "Global Cuisines",
      description: "Explore recipes from around the world and discover new family favorites.",
      available: true,
      action: () => router.push("/onboarding"),
    },
  ];

  return (
    <ScreenContainer className="p-6">
      <ScrollView contentContainerStyle={{ flexGrow: 1, paddingBottom: 40 }}>
        <View className="flex-1 gap-6">
          {/* Hero Section */}
          <View 
            style={{
              backgroundColor: colors.primary,
              borderRadius: 16,
              padding: 24,
              marginBottom: 8,
            }}
          >
            <Text style={{ fontSize: 32, fontWeight: 'bold', color: '#fff', marginBottom: 8 }}>
              Welcome to FamilyPlate! 🎉
            </Text>
            <Text style={{ fontSize: 16, color: '#fff', opacity: 0.9 }}>
              Your AI-powered family meal planning assistant is ready to help you end dinner debates.
            </Text>
          </View>

          {/* Quick Actions */}
          <View className="gap-3">
            <Text style={{ fontSize: 20, fontWeight: '600', color: colors.foreground }}>
              Quick Actions
            </Text>
            <View className="flex-row gap-3">
              <TouchableOpacity 
                style={{
                  flex: 1,
                  backgroundColor: colors.success,
                  paddingVertical: 16,
                  paddingHorizontal: 12,
                  borderRadius: 12,
                }}
                onPress={() => router.push("/generate-plan")}
              >
                <Text style={{ color: '#fff', textAlign: 'center', fontWeight: '600', fontSize: 15 }}>
                  📅 New Plan
                </Text>
              </TouchableOpacity>
              
              <TouchableOpacity 
                style={{
                  flex: 1,
                  backgroundColor: colors.primary,
                  paddingVertical: 16,
                  paddingHorizontal: 12,
                  borderRadius: 12,
                }}
                onPress={() => router.push("/dashboard")}
              >
                <Text style={{ color: '#fff', textAlign: 'center', fontWeight: '600', fontSize: 15 }}>
                  🍽️ View Plan
                </Text>
              </TouchableOpacity>
            </View>
          </View>

          {/* Features Grid */}
          <View className="gap-3">
            <Text style={{ fontSize: 20, fontWeight: '600', color: colors.foreground }}>
              Features
            </Text>
            <View className="gap-4">
              {features.map((feature, index) => (
                <TouchableOpacity
                  key={index}
                  disabled={!feature.available}
                  onPress={feature.action}
                  style={{
                    backgroundColor: colors.surface,
                    borderRadius: 12,
                    padding: 16,
                    borderWidth: 1,
                    borderColor: colors.border,
                    opacity: feature.available ? 1 : 0.6,
                  }}
                >
                  <View className="flex-row items-start gap-3">
                    <Text style={{ fontSize: 40 }}>{feature.icon}</Text>
                    <View style={{ flex: 1 }}>
                      <View className="flex-row items-center gap-2 mb-1">
                        <Text style={{ fontSize: 18, fontWeight: '600', color: colors.foreground }}>
                          {feature.title}
                        </Text>
                        {!feature.available && (
                          <View 
                            style={{
                              backgroundColor: '#F59E0B',
                              paddingHorizontal: 8,
                              paddingVertical: 2,
                              borderRadius: 6,
                            }}
                          >
                            <Text style={{ color: '#fff', fontSize: 11, fontWeight: '600' }}>
                              Coming Soon
                            </Text>
                          </View>
                        )}
                      </View>
                      <Text style={{ fontSize: 14, color: colors.muted, lineHeight: 20 }}>
                        {feature.description}
                      </Text>
                    </View>
                  </View>
                </TouchableOpacity>
              ))}
            </View>
          </View>

          {/* Settings Link */}
          <TouchableOpacity 
            style={{
              backgroundColor: colors.surface,
              paddingVertical: 14,
              paddingHorizontal: 16,
              borderRadius: 12,
              borderWidth: 1,
              borderColor: colors.border,
              marginTop: 8,
            }}
            onPress={() => router.push("/settings")}
          >
            <Text style={{ color: colors.foreground, textAlign: 'center', fontWeight: '600', fontSize: 16 }}>
              ⚙️ Settings
            </Text>
          </TouchableOpacity>
        </View>
      </ScrollView>
    </ScreenContainer>
  );
}
